// ignore_for_file: constant_identifier_names
library enums;

enum PrinterStatus { UNKNOWN, ERROR, NORMAL, ABNORMAL_COMMUNICATION, OUT_OF_PAPER, PREPARING, OVERHEATED, OPEN_THE_LID, PAPER_CUTTER_ABNORMAL, PAPER_CUTTER_RECOVERED, NO_BLACK_MARK, NO_PRINTER_DETECTED, FAILED_TO_UPGRADE_FIRMWARE, EXCEPTION }

enum PrinterMode { UNKNOWN, NORMAL_MODE, BLACK_LABEL_MODE, LABEL_MODE }

enum PrintAlign { LEFT, CENTER, RIGHT }

enum QrcodeLevel { LEVEL_L, LEVEL_M, LEVEL_Q, LEVEL_H }

enum BarcodeType { UPCA, UPCE, JAN13, JAN8, CODE39, ITF, CODABAR, CODE93, CODE128 }

enum BarcodeTextPos { NO_TEXT, TEXT_ABOVE, TEXT_UNDER, BOTH }

enum FontSize { XS, SM, MD, LG, XL }
